apiVersion: batch/v1
kind: CronJob
metadata:
  name: kplabs-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kplabs-pods
              image: busybox
              args: [ "/bin/sh", "-c", "date; echo Hello from the Kubernetes cluster" ]
          restartPolicy: OnFailure
