apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kplabs-updates
  name: kplabs-updates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kplabs-updates
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kplabs-updates
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
