apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kplabs-selector
  name: kplabs-selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kplabs-selector
  strategy: {}
  template:
    metadata:
      labels:
        app: kplabs-selector
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - image: nginx
        name: nginx
        resources: {}
