apiVersion: v1
kind: Service
metadata:
  labels:
    app: kplabs-service-selector
  name: kplabs-service-selector
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
