apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kplabs-cmdargs
  name: kplabs-cmdargs
spec:
  containers:
    - image: busybox
      name: kplabs-cmdargs
      command: ["sleep"]
      args: ["3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
